version: '3.8'

services:
  # jeager-all-in-one:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "16686:16686"
  #     - "14268"
  #     - "14250"

  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    ports:
      - "8888:8888" 
      - "8889:8889" 
      - "4317:4317" #otlp gRPC receiver
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config", "/etc/otel-collector-config.yaml" ]

  serviceA-app:
    image: golang:latest
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    working_dir: /app
    command: >
        sh -c "
        cd cmd &&
        go mod download &&
        go run serviceA.go ||
        echo 'Falha ao iniciar o servidor A. Verifique os logs para mais detalhes.'"
    depends_on:
      # - jeager-all-in-one
      - otel-collector
      - zipkin

  serviceB-app:
    image: golang:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: >
        sh -c "
        cd cmd &&
        go mod download &&
        go run serviceB.go ||
        echo 'Falha ao iniciar o servidor B. Verifique os logs para mais detalhes.'"
    depends_on:
      # - jeager-all-in-one
      - otel-collector
      - zipkin
